kumuluzee:
  name: listings-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://206.189.249.190/listings-service/
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ListingsDS
      connection-url: ${PG_HOST}
      username: ${PG_USER}
      password: ${PG_PASSWORD}
      pool:
        max-size: 5
  openapi-mp:
    ui:
      specification-server: http://206.189.249.190/listings-service/api-specs
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="f69f79f0-67ac-4674-9c9d-7cccc6aa6062-ls.logit.io"
                                  port="26288" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="trace" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  config:
    consul:
      agent: ${CONSUL_HOST}
# OPENAPI url http://206.189.249.190/listings-service/api-specs/ui/?url=http://206.189.249.190/listings-service/openapi&oauth2RedirectUrl=http://206.189.249.190/listings-service/api-specs/ui/oauth2-redirect.html#/